import './globals.css'
import { Source_Sans_3 } from 'next/font/google'

import Navigation from '@/components/Navigation';

// const inter = Inter({ subsets: ['latin'] })
const sourceSans = Source_Sans_3({ 
  subsets: ['latin'],
  weight: ["200", "400", "600"],
  variable: '--font-source-sans',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body id="body" className={`${sourceSans.variable} font-sourceSans`}>
        <Navigation/>
        {children}
      </body>
    </html>
  )
}
